### ISSUE TITLE
How do I recognize microexpressions use my own test examples?

### ISSUE THREAD

**Issue by YUZHIWANG-bug** [genbing99/MEAN_Spot-then-recognize#2]
Dear author, it is my great honor to star your project. I would like to ask you how to use your project to recognize micro-expressions in videos or pictures

**Comment by genbing99** [comment]
Very sorry for the late reply since the paper was under review.

The code is prepared to replicate the results obtained in the paper. We will provide a test demo in the future.

As for now, if you wish to use your own test examples, you can check out the codes in main.py and modify accordingly.

**Comment by YUZHIWANG-bug** [comment]
> Very sorry for the late reply since the paper was under review.
> 
> The code is prepared to replicate the results obtained in the paper. We will provide a test demo in the future.
> 
> As for now, if you wish to use your own test examples, you can check out the codes in main.py and modify accordingly.

Thanks for your reply! I will try.

**Comment by YUZHIWANG-bug** [comment]
> 

I'm sorry, but I want to ask, do you provide a pre-training model？

**Comment by genbing99** [comment]
You can use any model weights provided in the folder MEAN_Weights/*/spot_recog/

**Comment by YUZHIWANG-bug** [comment]
Thanks for your reply！ I will try

> You can use any model weights provided in the folder MEAN_Weights/*/spot_recog/
