### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by jxjiayou** [genbing99/MEAN_Spot-then-recognize#3]
Dear author, it is an honor to have read your code. I would like to ask why my dataset and code are the same as yours, and why there is so much difference in accuracy after complete training. I trained myself twice using the dataset SMIC-NIR and SMIC-VIS, with SMIC-NIR having an Accuracy Score of 0.3684 and 0.5294, and SMIC-VIS having an Accuracy Score of 0.6667 and 0.4828, respectively, which is somewhat different from the accuracy in the author's paper, May I ask why this is

**Comment by genbing99** [comment]
It is common for the results you obtained to differ from those in the paper. The results stated in the paper are typically obtained by averaging a number of repeated experiments.
